### ISSUE TITLE
Kunde anlegen - Speichern OK/NOK Message

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#105]
Wenn man einen Kunden speichert, dann kommt keine Information, ob das Anlegen des Kunden in Ordung war.

* => keine Message an den User
* => man wird automatisch an die Hauptseite geroutet
* => hatten wir schon mal auf der "alten Kunden" anlegen Seite

Hier fehlt die JS Function: wie auf der Seite Reservation List Page

	<script type="text/javascript">
		$(function() {
			toastr.options = {
				"closeButton": false,
				"debug": false,
				"newestOnTop": false,
				"progressBar": false,
				"positionClass": "toast-bottom-left",
				"preventDuplicates": false,
				"onclick": null,
				"showDuration": "300",
				"hideDuration": "1000",
				"timeOut": "5000",
				"extendedTimeOut": "1000",
				"showEasing": "swing",
				"hideEasing": "linear",
				"showMethod": "fadeIn",
				"hideMethod": "fadeOut"				
			}
			
		});
		
		function showFeedback(status) {
			if(status){
				toastr.success("","Buchung erfolgreich storniert");
			}else {
				toastr.error("","Buchung konte leider nicht storniert werden");	
			}
		}

**Comment by alex3772** [comment]
bitte auch die CustomerPage fixen (neu von mir erstellt)

**Comment by develope80** [comment]
=> Enhancement für Sprint 4 => neuer Task
