### ISSUE TITLE
Allgemein - Speichern OK/NOK Message

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#110]
* Kunde anlegen
* bitte auch die CustomerPage fixen (erstellt von @alex3772 )
* Zimmerverwaltung: auth. MA - Zimmer Daten editieren #5
* Zimmerverwaltung: auth. MA - neues Zimmer anlegen #6

Wenn man einen Kunden speichert, dann kommt keine Information, ob das Anlegen des Kunden in Ordung war.

=> keine Message an den User
=> man wird automatisch an die Hauptseite geroutet
=> hatten wir schon mal auf der "alten Kunden" anlegen Seite
Hier fehlt die JS Function: wie auf der Seite Reservation List Page

	<script type="text/javascript">
		$(function() {
			toastr.options = {
				"closeButton": false,
				"debug": false,
				"newestOnTop": false,
				"progressBar": false,
				"positionClass": "toast-bottom-left",
				"preventDuplicates": false,
				"onclick": null,
				"showDuration": "300",
				"hideDuration": "1000",
				"timeOut": "5000",
				"extendedTimeOut": "1000",
				"showEasing": "swing",
				"hideEasing": "linear",
				"showMethod": "fadeIn",
				"hideMethod": "fadeOut"				
			}
			
		});
		
		function showFeedback(status) {
			if(status){
				toastr.success("","Buchung erfolgreich storniert");
			}else {
				toastr.error("","Buchung konte leider nicht storniert werden");	
			}
		}

**Comment by alex3772** [comment]
ist bei mir in den top10 meiner ugliest hacks, aber hab ein funktionierendes beispiel in CustomerFormPanel.html, CustomerFormPanel.java und CustomerForm.java implementiert.

**Comment by develope80** [comment]
Review/QA => Kunde erstellen und editieren => OK
Review/QA => Reservierung erstellen => neune Kunden anlegen => OK
