### ISSUE TITLE
Buchung/Reservierung - gelöschte Reservierungen

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#118]
- Gelöschte Reservierungen werden weiterhin angezeigt.

Nicht nachvollziehbar.
Möglicherweise wird bei einer vorhandenen reservierung auf löschen gedrückt, aber die reservierung ist nicht löschbar und der benutzer hat die entsprechende meldung nicht gesehen.
weiters reklamiert:
- reservierungen in der vergangenheit sind löschbar

deshalb:

- löschen button nur anzeigen, falls die reservierung wirklich löschbar ist

**Comment by alex3772** [comment]
aus der email der LVA-Leitung:
Bzgl. Reservierungen wäre es eigentlich sauberer, den Button für diese Zeilen gar nicht anzuzeigen.

**Comment by develope80** [comment]
LVA: Bzgl. Reservierungen wäre es eigentlich sauberer, den Button für diese Zeilen gar nicht anzuzeigen.

**Comment by develope80** [comment]
Review/QA
=> Reservierung mit und ohne Rechnung erstellt => OK
