### ISSUE TITLE
Kunde anlegen - RuntimeException

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#121]
*) Es kommt leider nach wie vor zu einer Runtime Exception, wenn man beim Anlegen eines Kunden auf Speichern klickt und nicht alle Pflichtfelder befüllt sind.
Bitte hier entweder den Button solange Inaktivieren, bis man alles ausgefüllt hat oder entsprechende benutzerfreundliche Meldungen anzeigen.

=> MAIL an LVA => wird noch validiert

**Comment by alex3772** [comment]
not reproduceable in modern browser.

**Comment by develope80** [comment]
LVA: ich habe bislang immer mit Safari Version 8 getestet, bin nun allerdings aus von Ihnen genannten Gründen auf Firefox umgestiegen, 
dort ließ sich die Exception nicht re-produzieren. Dürfte also ein Browser spezifisches Problem gewesen sein, bitte nicht länger berücksichtigen.
