### ISSUE TITLE
Zimmerverwaltung:auth. MA - neues Zimmer anlegen

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#122]
**Rolle:** authentifizierter Mitarbeiter
**Ziel/Wunsch:** möchte ich ein neues Zimmer anlegen
**Nutzen:** um dieses Zimmer vermieten zu können

**Notiz:** 
Mindestens folgende Attribute können zu einem Zimmer gespeichert werden:
=>  **Pflichtfelder**
* Name oder Nummer
* Max. Belegzahl
* Preis EZ
* Preis DZ
* Preis Dreifachbelegung
* Preis EZ mit Kind
* Preis EZ mit 2 Kindern
* Preis DZ mit Kind

sobald die Seite erstellt wurde bitte den entsprechenden link im navigationpanel anpassen!

OK/NOK message auch einbauen, siehe mein kommentar unten.

**Comment by develope80** [comment]
# Logging nicht vergessen

**Comment by alex3772** [comment]
OK/NOK message kann man sich aus CustomerForm/-Panel abschauen.

**Comment by develope80** [comment]
Review/QA => OK
