### ISSUE TITLE
Reservierung - Menü

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#125]
Reservierungsverwaltung => 
=> Reservierungsliste
=> Reservierung anlegen

**Comment by develope80** [comment]
Wie bei der Kundenverwaltung
![menue](https://cloud.githubusercontent.com/assets/15790924/12400116/72ee4dba-be1e-11e5-9da0-30498a70cca5.PNG)

**Comment by alex3772** [comment]
hab das menu aus platzgründen _Reservierungen_ genannt.

**Comment by develope80** [comment]
Review/QA => OK
