### ISSUE TITLE
Zimmer -  Menü

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#126]
Zimmerverwaltung=> 
=> Zimmerliste
=> Zimmer anlegen

**Comment by develope80** [comment]
Wie bei der Kundenverwaltung
![menue](https://cloud.githubusercontent.com/assets/15790924/12400097/58ba4dd6-be1e-11e5-9d82-c902de5a5038.PNG)

**Comment by alex3772** [comment]
da zimmer anlegen seite noch nicht existiert, öffnet der link _Zimmer anlegen_ im moment noch die zimmerliste.
hab das menu aus platzgründen _Zimmer_ genannt.

**Comment by develope80** [comment]
Review/QA => OK
