### ISSUE TITLE
Kundenverwaltung: auth. MA - Kunden suchen

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#2]
<b>Rolle:</b> authentifizierter Mitarbeiter<br>
<b>Ziel/Wunsch:</b> möchte ich nach einen Kunden suchen können <br>
<b>Nutzen:</b> um ihn eindeutig zu identifizieren <br>
<b>Notiz: </b>Search criteria: Name, Geburtsdatum, Geschlecht, Rechnungsadresse, Firmenname(optional), Notiz, Telefonnummer, E-Mail, WEB, FAX

LVA =>

Die Seite zeigt von Anfang an eine Liste aller Kunden an.
Die Liste kann durch Suchkriterien eingeschränkt werden.
Folgende Suchkriterien werden zur Verfügung gestellt:

* Vorname
* Nachname
* Geburtsdatum
* Postleitzahl
* Firmenname

Das Ergebnis der Suche wird in einer Tabelle dargestellt.
Jede Reihe der Tabelle entspricht einem Kunden und die Spalten enthalten folgende Daten:

* Geschlecht
* Vorname
* Nachname
* Geburtsdatum
* Adresse
* Firmenname

Zusätzlich wird bei jeder Buchung ein Link angezeigt, der zu einer Detailansicht des Kunden führt.

- [x] #96 
- [x] #99
- [x] #98

**Comment by develope80** [comment]
[ ] #96 
[ ]
