### ISSUE TITLE
Kundenverwaltung: auth. MA - Kundendaten bearbeiten

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#3]
**Rolle:** authentifizierter Mitarbeiter
**Ziel/Wunsch:** möchte ich nachdem ich den Kunden gesucht habe, die Kundendaten bearbeiten können
**Nutzen:** um die Kundendaten aktuell zu halten
**Notiz:**Name, Geburtsdatum, Geschlecht, Rechnungsadresse, Firmenname(optional), Notiz, Rabatt, Telefonnummer, E-Mail, WEB, FAX

 - [x] Kundenverwaltung: auth. MA - Kunden suchen #2 (BACKLOG)

**Comment by develope80** [comment]
=> Wurde Sprint 3 mitentwickelt
=> Nochmaliger REVIEW/QA => OK
