### ISSUE TITLE
Nicht funktionale Anforderung -  Protokollierung

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#58]
Sämtliche Aktionen im System werden protokolliert und sind nachträglich nachvollziehbar.
- [x] Logging - Backend #100
- [x] Logging - Frontend #101
- [x] Logging - überall einbauen #107

**Comment by develope80** [comment]
Tasks abgeschlossen
Logging wird im nächsten Sprint erweitert
