### ISSUE TITLE
Zimmerverwaltung: auth. MA - neues Zimmer anlegen

### ISSUE THREAD

**Issue by chrisitananese** [Tomschi/uni-sese_ws15#6]
**Rolle:** authentifizierter Mitarbeiter
**Ziel/Wunsch:** möchte ich ein neues Zimmer anlegen
**Nutzen:** um dieses Zimmer vermieten zu können

**Notiz:** 
Mindestens folgende Attribute können zu einem Zimmer gespeichert werden:
=>  **Pflichtfelder**
* Name oder Nummer
* Max. Belegzahl
* Preis EZ
* Preis DZ
* Preis Dreifachbelegung
* Preis EZ mit Kind
* Preis EZ mit 2 Kindern
* Preis DZ mit Kind

- [x] Zimmerverwaltung:auth. MA - neues Zimmer anlegen #122 
- [x] Zimmer - Menü #126

**Comment by develope80** [comment]
LVA: Zimmer anlegen wäre eigentlich schon recht wichtig, da - wenn man keine Zimmer anlegen kann - ja alle weiteren Aktionen grundsätzlich nicht ausgeführt werden können und man immer einen DB Admin benötigt, der Zimmer adaptiert.
