### ISSUE TITLE
Applikationslog zur Verfügung stellen

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#62]
Der Kunde möchte den log einsehen können.
Wir müssen dafür sorgen, dass es für den Kunden eine Möglichkeit gibt den log zu bekommen.

**Comment by Tomschi** [comment]
[Dockerfile](https://files.zenhub.io/565ae4b2542087040e0381f4)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by develope80** [comment]
kein Docker file notwendig,
Deployment mit Procfile genügt,
web: java $JAVA_OPTS -jar target/sese*.jar -Dserver.port$PORT target/*.war -> sollte web: java $JAVA_OPTS -Dserver.port=$PORT -jar target/*.jar sein
solved by user @alex3772

**Comment by develope80** [comment]
http://logback.qos.ch/manual/appenders.html

**Comment by develope80** [comment]
http://logback.qos.ch/manual/appenders.html#DBAppender
* DBAppender is configured for your database
* key issue in configuring DBAppender is about setting its ConnectionSource object
* three tables used by logback to store logging event data.
       * logging_event table
       * logging_event_property
       * logging_event_exception

http://logback.qos.ch/manual/appenders.html#AccessDBAppender

**Comment by develope80** [comment]
Logback stellt ein Servlet (ViewStatusMessagesServlet) zur Verfügung, jedoch ist dies begrenzt auf 150 Einträge.
http://logback.qos.ch/manual/configuration.html#viewingStatusMessages
Das Servlet anzeigen funktioniert, jedoch wird nicht in das Statusmanager object geschrieben, obwohl der Loggercontext stimmt.

**Comment by develope80** [comment]
logback.xml fpr outputconsole und Database konfiguriert.
Tabellen werden angelegt, jedoch kommet eine Exception, dass der Dialect nicht unterstützt wird, von der Datenbank => die Database Appender Class unterstüzt kein Derby. Man müsste sich eine eigene Appender Class schreiben, wobei der Aufwand schon zu groß wäre.

**Comment by develope80** [comment]
Anhand des Servlets sieht man dass die logback.xml und der jdbc Treiber erkannt wird...
![logs](https://cloud.githubusercontent.com/assets/15790924/11767502/10bb9c18-a1b0-11e5-9896-58c729464354.PNG)

**Comment by develope80** [comment]
CREATE TABLE logging_event (
  timestmp          BIGINT NOT NULL,
  formatted_message LONG VARCHAR NOT NULL,
  logger_name       VARCHAR(256) NOT NULL,
  level_string      VARCHAR(256) NOT NULL,
  thread_name       VARCHAR(256),
  reference_flag    SMALLINT,
  arg0              VARCHAR(256),
  arg1              VARCHAR(256),
  arg2              VARCHAR(256),
  arg3              VARCHAR(256),
  caller_filename   VARCHAR(256),
  caller_class      VARCHAR(256),
  caller_method     VARCHAR(256),
  caller_line       CHAR(4),
  event_id          BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
 );

CREATE TABLE logging_event_property (
  event_id          BIGINT NOT NULL,
  mapped_key        VARCHAR(254) NOT NULL,
  mapped_value      LONG VARCHAR,
  PRIMARY KEY(event_id, mapped_key),
  FOREIGN KEY (event_id) REFERENCES logging_event(event_id)
);

CREATE TABLE logging_event_exception (
  event_id          BIGINT NOT NULL,
  i                 SMALLINT NOT NULL,
  trace_line        VARCHAR(256) NOT NULL,
  PRIMARY KEY(event_id, i),
  FOREIGN KEY (event_id) REFERENCES logging_event(event_id)
);

**Comment by develope80** [comment]
Auf HSQLDB umgeswitched, SQL Queries umgeschrieben, logback.xml und application properties angepasst, pom.xml angepasst

**Comment by develope80** [comment]
=> Dialect gefunden, jedoch wird die Tabelle nicht gefunden oder die Privilegien

**Comment by develope80** [comment]
=>ocal file DB angelegt, selbes Problem,  gemeinsam mit @Tomschi  analysiert

**Comment by develope80** [comment]
=> Logfile momentan über Heroku möglich
Implementation wird über eine Entity gemacht Bsp Logentrys...

**Comment by develope80** [comment]
=> TASK wird geschlossen, und ein neues ISSUE dafür gemacht

**Comment by develope80** [comment]
neuer Task #100 , #101
