### ISSUE TITLE
Seite zur Auswahl von Datum und Personen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#65]
Eigene Seite auf der folgende Elemente zu finden sind:
* 2 comboboxen zur auswahl der anzahl an personen
  * erwachsene
  * kinder
* 2 datepicker für den buchungszeitraum
  * start
  * ende

**Comment by develope80** [comment]
* 2 comboboxen zur auswahl der anzahl an personen vorhanden
* 2 datepicker für den buchungszeitraum 
vorhanden => OK
