### ISSUE TITLE
Zimmersuchseite fixen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#66]
Die Zimmerseite wirft bei diversen Eingabewerten Fehler (zB "asdsd").
Weiters muss man eines der Zimmer auswählen können um diese Seite in den Buchung erstellen Prozess einbinden zu können.

**Comment by alex3772** [comment]
hab ein eigenes panel für die zimmerauswahl implementiert.

**Comment by develope80** [comment]
Zimmerauswahl mit Panel vorhanden, Button auswählen => OK
