### ISSUE TITLE
Abschluß der Buchung

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#68]
* Rabattberechnung
* speichern
* Meldung über Erfolg an Benutzer
* Loggen

**Comment by develope80** [comment]
Wenn man nach der Auflistung der Reservierungsdaten die Reservierung bestätigt - Button "Reservierung bestätigen",  
* bekommt der User keine Meldung, dass die Reservierung erfolgreich durchgeführt worden ist
* der User wird direkt auf die Mainpage geroutet
  * Keine Meldung über Erfolg an User
 => NOK

**Comment by develope80** [comment]
Popup, danach Weiterleitung zur Buchung
Option: Meldung anzeigen, dass Buchung erledigt ist mit der Buchungsnummer

**Comment by alex3772** [comment]
on success: redirect zur detailansicht der buchung

**Comment by alex3772** [comment]
onfailure: message wird angezeigt

**Comment by develope80** [comment]
=> OK
