### ISSUE TITLE
Kundenmenü und item "Kunde anlegen" erstellen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#69]
Hauptapplikationsmenü rechts oben bekommt ein Menü "Kunden".
Darin wird der Eintrag "Kunde anlegen" hinzugefügt, der die Seite zum anlegen eines neuen Kunden öffnet.

**Comment by Tomschi** [comment]
Eintrag Kunde wurde hinzugefügt. Kunde anlegen wird bei erstellungen der Seite eingefügt.

**Comment by develope80** [comment]
Das Menü "Kunden" wurde zwar angelegt, jedoch ist "Kunden anlegen" kein Sub-Menü.
"Kunden anlegen" soll als Sub-Menü angelegt werden.

**Comment by develope80** [comment]
Kundenverwaltung 
* Kunden Liste
* Kunden anlegen
=> OK
