### ISSUE TITLE
Kunde anlegen Seite fixen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#70]
* kein Username und Passwort Eingabefeld.
* loggen
* verifzieren, dass speichern funktioniert.
* wenn möglich auf 2 Spalten aufteilen

**Comment by develope80** [comment]
* kein Username und Passwort Eingabefeld.
	* noch vorhanden => NOK
	* Option
		* Auth Mitarbeiter kann Username und Passwort für Kunden anlegen
		* dh. Username und Passwort sollte, wenn ein auth. MA einen Kunden anlegt OPTIONAL sein
* loggen
* verifzieren, dass speichern funktioniert.
	* funktioniert, erst wenn man alle Datein eingegeben hat
	* die Daten werden nicht validiert
	* keine Überprüfung auf Pflichfelder
		* keine Meldung, wenn man nicht alle Daten(Pflichtfelder) eingegeben hat
	* es kommt keine Meldung, dass die Daten erfolgreich gespeichert wurden.
	* nach dem Speichern der Daten wird man sofort auf die Mainpage geroutet
	* siehe Pflichtenheft (Pflichtfelder)
		• Name
		• Geburtsdatum
		• Geschlecht
		• Rechnungsadresse
		• Firmenname (optional)
		• Notiz
		• Rabatt
		• Telefonnummer
		• E-Mail
		• WEB
		• FAX
* Geburtsdatum fehlt
* Kunde anlegen
	* heisst jetzt Konto registrieren => NOK
		* sollte Kunden anlegen heissen
		* Button "Registrieren" muss auch umbenannt werden

**Comment by alex3772** [comment]
hab das CustomerForm für einen anderen task umgeschrieben.
bitte dieses form auch für die kunden anlegen seite verwenden.
ich hab folgendes gefixt:
* username und password entfernt
* geburtsdatum hinzugefügt

**Comment by develope80** [comment]
Review/QA => OK
