### ISSUE TITLE
Alle Suchkriterien getrennt einbauen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#71]
Folgende Suchkriterien können gleichzeitig verwendet werden (getrennte Eingabefelder):
* Kunde
* Zimmer
* Start
* Ende

**Comment by develope80** [comment]
Datepicker vorher notwendig

**Comment by develope80** [comment]
Review/QA => Zimmer suchen & Reservierungen suchen  => OK
