### ISSUE TITLE
Link zur Detailansicht der Buchung einbauen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#72]
Die Suchergebnisse sollen einen Link zur Detailansicht einer Buchung enthalten.

**Comment by develope80** [comment]
Link auf Details vorhanden und funktioniert auch => OK
![detailslinkreservierung](https://cloud.githubusercontent.com/assets/15790924/11763610/23971090-a112-11e5-99e6-160b704e4507.PNG)
