### ISSUE TITLE
Rechnungs Buttons zur Detailansicht einer Buchung hinzufügen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#74]
Bei der Detailansicht einer Buchung sollen die Buttons:
* Rechnung erstellen
* Rechnung ansehen
hinzugefügt werden.
Ist ist immer nur einer der Buttons sichtbar, je nachdem ob schon eine Rechnung existiert oder nicht.

Bei Betätigung des Rechnung erstellen buttons wird:
* die Rechnung in der Datenbank angelegt
* ein entsprechender eintrag im log erstellt
* und zu der Seite zum anzeigen der Rechnung weitergeleitet

Bei Betätigung des Rechnung erstellen buttons wird zu der Seite zum anzeigen der Rechnung weitergeleitet.

**Comment by alex3772** [comment]
im branch invoice.
(da die implementierung der detailseite und des services noch nicht fertig ist)

**Comment by develope80** [comment]
=> OK
