### ISSUE TITLE
Button zum stornieren einer Buchung

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#76]
Ein button zum stornieren einer buchung ist in der detailansicht einer Buchung verfügbar wenn:
* die stornierfrist nicht abgelaufen ist (siehe user story)
* noch keine rechnung erstellt wurde

Bei klick auf den Button wird die Buchung storniert und ein entsprechender Eintrag im log angelegt.

**Comment by develope80** [comment]
Bitte keine neuen Branches machen, den Branch bitte wieder löschen und in den Developement Branch committen... ist so die Vorgangsweise seit kurzen => deswegen haben wir nur 3 Branches (Master, Developement und Testing)

**Comment by develope80** [comment]
Button zum stornieren ist verfügba.
* Neue Reservierung erstellt, danach den "Löschen" Button betätigt -> jedoch wurde die neue Buchung/Reservierung mit der Fehlermeldung "Buchung konnte leider nicht storniert werden" nichts storniert => 
Grund: laut Pflichtenheft "STORNO": Stornierung innerhalb einer bestimmten Zeit vor dem Aufenthalt möglich.
* Ein vorhandene Buchung kann ganz normal storniert werden, mit einer Meldung, dass die Buchung storniert wurde => OK
* Genaue Spezifizierung für Checkin/Checkout notwendig => NEW ISSUE
