### ISSUE TITLE
Buchung storniert Meldung

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#77]
nach der stornierung einer buchung wird eine meldung über erfolg oder fehler angezeigt und der benutzer zur buchungssuche weitergeleitet.

**Comment by chrisitananese** [comment]
Da ein submit einen page reload macht, wird die Feedback Anzeige eig. abgebrochen bevor sie überhaupt erschienen ist.
Als Temporäre Lösung für diesen Sprint wird der Reload für 1 Sek verzögert

**Comment by develope80** [comment]
Hallo, kann man das nicht im lifecylce von Wicket abhandeln?

**Comment by develope80** [comment]
Meldungen werden angezeigt.
