### ISSUE TITLE
2 heroku instanzen zum laufen bringen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#78]
wie/ob können wir 2 apps auf heroku deployen?

**Comment by develope80** [comment]
How heroku works:
https://devcenter.heroku.com/articles/how-heroku-works

Managing Multiple Environments:
 https://devcenter.heroku.com/articles/multiple-environments

Unter Heroku habe ich 2 Webapp mit meinem Account zum Testen erstellt.
Es wurde jeweils der spezifische Branch mit den Procfiles Deployed:

Befehle:
DEV
heroku create --remote staging
git push staging developement:master
heroku ps --remote staging

PROD
heroku create --remote production
git push production master:master
heroku ps --remote production

Links für die 2 Instanzen:
DEV
https://glacial-spire-9574.herokuapp.com/

PROD:
https://enigmatic-coast-7013.herokuapp.com/

-> Somit sind 2 getrennte Instanzen möglich.

Allerdings muss Travis CI den richtigen Branch für die jeweilige App verwenden.

**Comment by develope80** [comment]
Heroku Instanzen laufen:
TESTBRANCH: http://sese-ws15-test.herokuapp.com
MASTERBRANCH: http://sese-ws15.herokuapp.com
