### ISSUE TITLE
Neu anlegen eines Kunden in CustomerSelectPanel einbauen

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#82]
laut spec soll während der Buchungserstellung entweder ein Kunde ausgewählt oder ein Kunde angelegt werden können.
im moment kann im panel CustomerSelectPanel nur ein Kunde gewählt werden.
deshalb muss man das kunde anlegen noch irgendwie einbauen.

**Comment by chrisitananese** [comment]
@alex3772  Du meinst einfach im Panel einen Button oder Icon-Button welcher auf Kunden erstellen zeigt?
Das wäre kein Prob., schwieriger wird es wenn man nach dem Anlegen wieder zurück geleitet werden will

**Comment by alex3772** [comment]
fertig mit folgender anmerkung:
ich verwende das CustomerForm. Das hat noch ein paar bugs, die sind in Task #70 beschrieben. die seite aus dem task sollte auch das CustomerForm verwenden und die entsprechenden bugs fixen.
