### ISSUE TITLE
ReservationService.create(3) muss prüfen ob das Zimmer noch verfügbar ist.

### ISSUE THREAD

**Issue by alex3772** [Tomschi/uni-sese_ws15#83]
da zwischen der auswahl des zimmers und dem abschluss der reservierung das zimmer schon belegt werden kann muss die methode ReservationService.create(3) vor dem speichern nochmal prüfen ob das zimmer noch frei ist.

**Comment by develope80** [comment]
Review/QA => OK
Information an User, wenn das Zimmer schon gebucht worden ist => "Zimmer wurde bereits von einem anderen Kunden reserviert."
