### ISSUE TITLE
Zimmersuchseite fixen

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#86]
* Die Zimmerseite wirft bei diversen Eingabewerten Fehler (zB "asdsd").

 * Fehlermeldung:
Last cause: The model of Select component [24:search_form:searchType] is not of type java.util.Collection, but more then one SelectOption component has been selected. Either remove the multiple attribute from the select tag or make the model of the Select component a collection

   Root cause:
 org.apache.wicket.WicketRuntimeException: The model of Select component [24:search_form:searchType] is not of type java.util.Collection, but more then one SelectOption component has been selected. Either remove the multiple attribute from the select tag or make the model of the Select component a collection

etc...
* Weiters muss man eines der Zimmer auswählen können um diese Seite in den Buchung erstellen Prozess einbinden zu können.

**Comment by Tomschi** [comment]
Wird im Zuge von #71 behoben
