### ISSUE TITLE
Reservierungen erstellen - Validierung

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#88]
1) Es ist möglich, Reservierungen zu erstellen, deren Ende vor dem Beginn liegt sowie Reservierungen, die gänzlich in der Vergangenheit liegen.
Hier sollte bitte eine Validierung stattfinden, bevor man weiter zur Zimmerauswahl kommt.

**Comment by alex3772** [comment]
enddatum vor startdatum noch nicht gefixt.
vl sollte man auch schauen, dass von den personen her maximal 3 personen(kinder+erwachsene) auswählbar sind.

**Comment by alex3772** [comment]
pffh, das i eigentlich schon gefixt, vergessen den task zu verschieben....

**Comment by develope80** [comment]
Review/QA => OK
