### ISSUE TITLE
Reservierungen erstellen - Zimmer Auswahl

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#89]
2) Im Schritt nach der Zimmerauswahl wird in der Tabelle anstelle des ausgewählten Zimmers erneut der "Auswahl"-Button angezeigt

**Comment by alex3772** [comment]
ich habe angenommen, dass nur die spaltenüberschrift nicht korrekt war...
kommt darauf an welche antwort von der LVA-Leitung kommt.

**Comment by develope80** [comment]
Review/QA => Warten auf die Kundenantwort

**Comment by develope80** [comment]
noch keine LVA/Kundenantwort => Eventuell kein BUG sondern ein Changerequest => neuer Task für Sprint 4 wird gelogged
