### ISSUE TITLE
Kunde anlegen -  Runtime Exception

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#92]
3) Wenn Pflichtfelder nicht eingegeben werden und man schließt ab, kommt es zu einer Runtime Exception. Diese wird im Browser angezeigt.

**Comment by alex3772** [comment]
wird sich von selbst erledigen wenn #90 und #91 erledigt sind

**Comment by develope80** [comment]
Review/QA => OK
Nach Eingabe der Pflichtfelder und nach dem Speichern der Daten kommt keine Exception mehr
