### ISSUE TITLE
Kunde anlegen - negative Rabatte

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#95]
6) Man kann negative Rabatte angeben

**Comment by develope80** [comment]
max 100%, default empty => Textbox

**Comment by chrisitananese** [comment]
Funktioniert bei mir nur browser-abhängig

**Comment by develope80** [comment]
Review/QA => OK
IE => Eingabe des Rabettes mit min 0 und max 100 => OK
Google Chrome und Firefox Auswahl 0 - 100 => OK
Validierung und InfoMessage => OK
