### ISSUE TITLE
Kundenverwaltung - auth. MA - Suchkriterien

### ISSUE THREAD

**Issue by develope80** [Tomschi/uni-sese_ws15#99]

**Comment by alex3772** [comment]
hab auch noch ein paar sachen, die aus #2 fehlten gefixt (zb kunde detailansicht)

**Comment by develope80** [comment]
Review/QA => OK
Suchfilter => OK
Kunden Detailansicht => Änderungen speichern => OK
jeoch keine Meldung dass die Änderungen gespeichert worden sind => wird später gefixed
